[package]
name = "czh-http-server"
version = "0.1.0"
edition = "2021"
description = "A simple http server"
license = "MIT"
repository = "https://github.com/bigoldcat123/czh-http-server.git"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.133"
